# Generated by Django 5.0.2 on 2024-07-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0002_newuser_agency_percentage_newuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_doc_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
