# Generated by Django 5.0.2 on 2024-07-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0004_prototype_author_alter_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='prototype',
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_num', models.CharField(max_length=20)),
                ('subscri_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('prototype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_prototypes', to='lumenapp.prototype')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_house', to='lumenapp.houses'),
        ),
    ]
