# Generated by Django 5.0.2 on 2024-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0005_remove_subscription_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
