# Generated by Django 5.0.2 on 2024-07-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0006_subscription_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='house_num',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscri_price',
        ),
    ]
