# Generated by Django 5.0.2 on 2024-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0007_remove_subscription_house_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
