# Generated by Django 5.0.2 on 2024-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0008_subscription_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_available',
        ),
    ]
