# Generated by Django 5.0.2 on 2024-07-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0009_remove_subscription_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='prototype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_prototypes', to='lumenapp.prototype'),
        ),
    ]
