# Generated by Django 5.0.2 on 2024-07-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenapp', '0010_alter_houses_prototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_house', to='lumenapp.houses'),
        ),
    ]
